config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'
  resources :books
  resources :categories
  resources :authors
  resources :reviews
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      alias_action :create, :read, :update, :destroy, to: :crud

      if user.admin?
        can :manage, :all
      elsif user.role == 'user'
        can :crud, Book
        can :crud, Author
        can :crud, Review
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, through: :author_books
  has_many :author_books

  validates :name, presence: true
  validates :surname, presence: true
  validates :desc, presence: true
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors, through: :author_books
  has_many :author_books
  belongs_to :user
  has_many :categories, through: :ganre_from_books
  has_many :ganre_from_books
  has_many :reviews

  mount_uploaders :pictures, PictureUploader
  serialize :pictures, JSON

  validates :title, presence: true
  validates :desc, presence: true

  def rate
    @result = 0
    self.reviews.each do |result|
      @result = @result + result.rate
    end
    if @result == 0
      @result = 0
    else
      @result = @result / self.reviews.count
      @result = eval(sprintf("%8.1f",@result))
    end
  end

  def rate_author

  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author
  has_many :books, through: :ganre_from_books
  has_many :ganre_from_books
end

app/models/ganre_from_book.rb
class GanreFromBook < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.name.capitalize! }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_many :reviews

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to main_app.root_url, :alert => exception.message }
    end
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:admin, :name, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:admin, :name, :role])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  load_and_authorize_resource
  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to root_path, notice: 'Author added!' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def author_params
    params.require(:author).permit(:name, :desc, :surname)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource

  def new
    @book = Book.new
    @authors = Author.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @pictures = @book.pictures
    @reviews = @book.reviews
    @review = Review.new
  end

  def index
    @books = Book.paginate(:page => params[:page], per_page: 6)
    @categories = Category.all
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_path(@book), notice: 'The book is under moderation and will be added after approval by the administrator' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end

  end

  private

  def book_params
    params.require(:book).permit(:title, :desc, :user_id, {pictures: []}, author_ids: [] )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to :back, notice: 'Review added!' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { redirect_to :back, notice: 'Enter all inputs!' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:success] = "Review deleted!"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "ERROR!"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def review_params
    params.require(:review).permit(:body, :rate, :user_id, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for @author do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, required: true, autofocus: true %>
  <%= f.input :surname, required: true %>
  <%= f.input :desc, required: true, label: "Description" %>
  <%= f.button :submit, class: "btn-primary btn-sm" %>
<% end %>

app/views/authors/new.html.erb
<h3>Add new Author</h3>
<%= render 'form' %>

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.error_notification message: 'Something went wrong' %>
  <%= f.input :title, required: true, autofocus: true %>
  <%= f.input :authors, collection: @authors, input_html: { multiple: true }, required: true  %>
  <%= f.input :categories, collection: @categories, input_html: { multiple: true }, required: true %>
  <%= f.input :desc, required: true %>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.file_field :pictures, multiple: true, class: "btn-primary btn-sm" %><br>
  <%= f.button :submit, class: "btn-primary btn-sm" %>
<% end %>

app/views/books/index.html.erb
<div class="row">
<h4>All books</h4>
<!-- <p>Select category:
  <% @categories.each do |category| %>
    <% if category == @categories.last %>
      <%= link_to category.name, category_path(category.id) %>.
    <% else %>
      <%= link_to category.name, category_path(category.id) %>,
    <% end %>
  <% end %>
</p> -->
<% @books.each do |book| %>
<div class="col-md-6">
  <div class="col-md-4">
    <%= image_tag book.pictures[0].url(:some)%>
  </div>
  <div class="col-md-6">
    <%= link_to book.title, book_path(book.id)  %><br>
    <i><%= h truncate(book.desc, :length => 50) %></i><br>
    <%= book.user.name %><br>
    (<%= book.rate %>, <%= book.reviews.count %> reviewers)<br>
    <%= book.pictures.count %> photos
  </div>
</div>
<% end %>
  <br clear="all">
  <div class="col-md-5 col-md-offset-3">
    <p align="center">
      <%= will_paginate @books, renderer: BootstrapPagination::Rails %>
    </p>
  </div>
</div>

app/views/books/new.html.erb
<h3>Add new book</h3>
<%= render 'form' %>

app/views/books/show.html.erb
<h3><%= @book.title %></h3>

<div class="row">
  <div class="col-md-2">
    <%= image_tag @pictures[0].url(:some) %>
  </div>

  <div class="col-md-10">
  <p>Description</p>
    <%= @book.desc %>
  </div>

  <div class="col-md-10">
    <% @pictures.each do |pic| %>

      <div class="col-md-3">
      <br>
        <%= image_tag pic.url(:thumb) %>
      </div>
    <% end %>
  </div>
  <br clear="all">
  <hr>
  <h4><strong><i>Information</i></strong></h4>

  <p><strong>Author:</strong>
    <% @book.authors.each do |author| %>
      <% if @book.authors.last == author %>
        <%= author.name %> <%= author.surname %>.
      <% else %>
        <%= author.name %> <%= author.surname %>,
      <% end %>
    <% end %>
  </p>

  <p><strong>Category:</strong>
    <% @book.categories.each do |category| %>
      <% if @book.categories.last == category %>
        <%= category.name %>.
      <% else %>
        <%= category.name %>,
      <% end %>
    <% end %>
  </p>

  <p><strong>Book rating:</strong>
    <% if @book.rate == 0 %>
      <i>Rate nill</i>
    <% else %>
      <%= @book.rate %>
    <% end %>
  </p>

  <p>
    <strong>Author rating:</strong>

  </p>

  <p>
    <strong>Added by:</strong>
    <%= @book.user.name %>
    <i><%= @book.updated_at.to_formatted_s(:long_ordinal) %></i>
  </p>

  <hr>
  <h4><strong><i>Reviews</i></strong></h4>
  <% if @reviews.count == 0 %>
    <strong><i>No reviews yet</i></strong>
  <% else %>
    <% @reviews.each do |review| %>
      <p>On <%= review.updated_at.to_formatted_s(:long_ordinal) %>, <%= review.user.name %> said:<br>
      <%= review.body %><br>
      Book rating: <%= review.rate %><br>
      <% if review.user == current_user %>
        <% if can? :destroy, Review %>
          <span title="Delete review">
            <%= link_to '', review_path(review), method: :delete, class: "btn btn-danger btn-sm glyphicon glyphicon-remove", remote: true %>
          </span>
        <% end %>
      <% end %>
      </p>
    <% end %>
  <% end %>
  <% if can? :create, Review %>
  <% unless @reviews.where(user_id: current_user.id).count != 0 %>
      <h2 class="btn btn-info btn-block" href="#review" data-toggle="collapse">Add review</h2><br clear="all">
      <div id="review" class="collapse in">
        <%= render '/reviews/form' %>
      </div>
  <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinishApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>

    <nav id="top_nav" class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="navbar-nav navbar-right">
            <% if user_signed_in? %>
              <ul>
              <p class="navbar-text">

                <strong><%= link_to "Привет, #{current_user.name}", edit_user_registration_path(current_user), class: 'navbar-link' %></strong> |
                <%= link_to "Add new book", new_book_path %> |
                <%= link_to "Add new author", new_author_path %>
              </p>
              <% if current_user.admin? %>
                <ul class="nav navbar-nav">
                  <li>
                    <li><%= link_to 'Перейти на административную панель', admin_dashboard_path %></li>
                  </li>
                </ul>
              <% end %>
                <%= link_to 'Выход', destroy_user_session_path, method: :delete,  class: 'btn btn-primary navbar-btn'%>
              </ul>
              <% else %>
               <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary navbar-btn' %> |
               <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary navbar-btn' %>
            <% end %>
          </ul>
          <a class="navbar-brand" href="/">Library</a>
        </div>
      </nav>


    <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> col-md-8 col-md-offset-2">
        <p align="center"><%= value %></p>
      </div>
      <br clear="all">
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.error_notification %>
  <%= f.input :body, label: "Review", required: true, autofocus: true %>
  Rating: <%= f.select :rate, [1, 2, 3, 4, 5] %>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
  <%= f.input :book_id, :as => :hidden, :input_html => { :value => @book.id } %>
  <%= f.button :submit, class: "btn-primary btn-sm" %>
<% end %>